Repository AY2223S2-CS2103T-T13-4/tp, pull requests merged in 2023-03, with the labels that each got.

#66 fix user guide as Title prefix clashes with tag prefix
  docs/UserGuide.md
Labels: bug

#75 Update add command and replace Phone with Progress
  docs/UserGuide.md
  src/main/java/seedu/library/logic/commands/AddCommand.java
  src/main/java/seedu/library/logic/parser/AddCommandParser.java
  src/main/java/seedu/library/logic/parser/CliSyntax.java
  src/main/java/seedu/library/logic/parser/ParserUtil.java
  src/main/java/seedu/library/model/bookmark/Bookmark.java
  src/main/java/seedu/library/model/bookmark/Phone.java
  src/main/java/seedu/library/model/bookmark/Progress.java
  src/main/java/seedu/library/model/util/SampleDataUtil.java
  src/main/java/seedu/library/storage/JsonAdaptedBookmark.java
  src/main/java/seedu/library/ui/BookmarkCard.java
Labels: priority.High

#139 1.3 update genre
  src/main/java/seedu/library/logic/commands/GenreCommand.java
  src/main/java/seedu/library/logic/parser/LibraryParser.java
  src/main/java/seedu/library/model/bookmark/Genre.java
  src/main/java/seedu/library/model/util/SampleDataUtil.java
  src/test/data/JsonLibraryStorageTest/invalidAndValidBookmarkLibrary.json
  src/test/data/JsonLibraryStorageTest/invalidBookmarkLibrary.json
  src/test/java/seedu/library/model/bookmark/GenreTest.java
Labels: type.Task

#140 Update DG and UML Diagrams
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
Labels: documentation.DeveloperGuide

#148 Fix tags edit
  src/main/java/seedu/library/logic/commands/EditCommand.java
  src/main/java/seedu/library/logic/parser/AddTagCommandParser.java
Labels: bug

#155 Update Test cases for pre-defined Genre
  src/test/data/JsonSerializableLibraryTest/duplicateBookmarkLibrary.json
  src/test/data/JsonSerializableLibraryTest/typicalBookmarksLibrary.json
  src/test/java/seedu/library/logic/commands/CommandTestUtil.java
  src/test/java/seedu/library/logic/parser/ParserUtilTest.java
  src/test/java/seedu/library/model/bookmark/BookmarkTest.java
  src/test/java/seedu/library/testutil/BookmarkBuilder.java
  src/test/java/seedu/library/testutil/TypicalBookmarks.java
Labels: type.Task

#157 Create Ratings for Bookmarks
  src/main/java/seedu/library/logic/commands/AddCommand.java
  src/main/java/seedu/library/logic/commands/EditCommand.java
  src/main/java/seedu/library/logic/parser/AddCommandParser.java
  src/main/java/seedu/library/logic/parser/CliSyntax.java
  src/main/java/seedu/library/logic/parser/ParserUtil.java
  src/main/java/seedu/library/model/bookmark/Bookmark.java
  src/main/java/seedu/library/model/bookmark/Rating.java
  src/main/java/seedu/library/model/util/SampleDataUtil.java
  src/main/java/seedu/library/storage/JsonAdaptedBookmark.java
  src/main/java/seedu/library/ui/BookmarkListPanel.java
Labels: type.Task

#167 Update UG and DG to include Genre and Rating
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation.UserGuide, documentation.DeveloperGuide

#190 Update ug sort
  docs/UserGuide.md
  src/main/java/seedu/library/ui/ZoomView.java
Labels: documentation.UserGuide
